name: Deploy Latest Release to Vultr

on:
  workflow_dispatch: 
  release: 
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download latest release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: MattRyanCo/COTAdirectory
          file: "https://github.com/MattRyanCo/COTAdirectory\*\\tags\*\\.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload files to Vultr via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: ${{ secrets.VULTR_USERNAME }}
          key: ${{ secrets.VULTR_SSH_KEY }}
          port: 22
          source: "https://github.com/MattRyanCo/COTAdirectory\*\\tags\*\\.zip"
          target: /root/www/cotadirectory

      - name: Set permissions on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: ${{ secrets.VULTR_USERNAME }}
          key: ${{ secrets.VULTR_SSH_KEY }}
          port: 22
          script: |
            chown -R www-data:www-data /root/www/cotadirectory
